
# Site Settings
title:               Yifan Zhu
tagline:             PhD Student, Statistician
description:
baseurl:            #"/Fanne"
url:                #"https://fanne-stat.github.io"
github:
  url:               "https://fanne-stat.github.io"
author:
  name:              "Yifan Zhu"
  email:             "yifanzhu@iastate.edu"
  github:            "fanne-stat"
  facebook:          "yifan.zhu.357"
  linkedin:          "yifanzhu1"
paginate:            5


# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]

